<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEIITLxV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEIITLxV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEIITLxV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEIITLxV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEIITLxV\App_KernelDevDebugContainer([
    'container.build_hash' => 'EIITLxV',
    'container.build_id' => '52870a81',
    'container.build_time' => 1746716849,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEIITLxV');
