<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIJYvWv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIJYvWv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIJYvWv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIJYvWv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOIJYvWv\App_KernelDevDebugContainer([
    'container.build_hash' => 'OIJYvWv',
    'container.build_id' => '21e97c4d',
    'container.build_time' => 1746741256,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIJYvWv');
