<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVQBjxLL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVQBjxLL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVQBjxLL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVQBjxLL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVQBjxLL\App_KernelDevDebugContainer([
    'container.build_hash' => 'VQBjxLL',
    'container.build_id' => 'b9ae529e',
    'container.build_time' => 1746727947,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVQBjxLL');
